version: '3.7'

services:
  app:
    build: .
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=postgresql://docker:docker@db:5432/example?schema=public
    depends_on:
      - db
  db:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=example
    volumes:
      - example_pg_data:/bitnami/postgresql

volumes:
  example_pg_data: